###
# This file is autogenerated from https://github.com/buildpacks/pack/tree/main/.github/workflows/delivery/homebrew/
# Changes should be committed there. 
###
class Pack < Formula
  desc "A CLI for building apps using Cloud Native Buildpacks"
  homepage "https://github.com/buildpacks/pack"
  if OS.mac?
    url "https://github.com/buildpacks/pack/releases/download/v0.14.2/pack-v0.14.2-macos.tgz"
    sha256 "5c7fcdc03f2ee142a19154b4675dd81bff8014ca6e89ebcfea5d3c6bae496cbf"
  else 
    url "https://github.com/buildpacks/pack/releases/download/v0.14.2/pack-v0.14.2-linux.tgz"
    sha256 "cb176c106f815c2f675bb000ee337993edbe747fae578e67ddd8884c86c6ab1b"
  end

  bottle :unneeded

  def install
    bin.install "pack"
  end
end
