###
# This file is autogenerated from https://github.com/buildpacks/pack/tree/main/.github/workflows/delivery/homebrew/
# Changes should be committed there. 
###
class Pack < Formula
  desc "A CLI for building apps using Cloud Native Buildpacks"
  homepage "https://github.com/buildpacks/pack"
  version "0.32.0"
  version_scheme 1

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/buildpacks/pack/releases/download/v0.32.0/pack-v0.32.0-macos-arm64.tgz"
    sha256 "a11cda83d3fe20bb04f6f552051f0b7ef9a6fb7c52a79e1bf83e311f5d6d5745"
  elsif OS.mac?
    url "https://github.com/buildpacks/pack/releases/download/v0.32.0/pack-v0.32.0-macos.tgz"
    sha256 "61aa68ae59b3f2844dc7bbb0380cab4d85987349a1ab4a75ded4d04af65b5835"
  else 
    url "https://github.com/buildpacks/pack/releases/download/v0.32.0/pack-v0.32.0-linux.tgz"
    sha256 "f559cf23593240580f9a0c1936b5b1f590cb99f1a3c5da12dde15057703460bd"
  end

  def install
    bin.install "pack"
  end
end
