###
# This file is autogenerated from https://github.com/buildpacks/pack/tree/main/.github/workflows/delivery/homebrew/
# Changes should be committed there. 
###
class Pack < Formula
  desc "A CLI for building apps using Cloud Native Buildpacks"
  homepage "https://github.com/buildpacks/pack"
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/buildpacks/pack/releases/download/v0.23.0/pack-v0.23.0-macos-arm64.tgz"
    sha256 "7d1b42b6bb9e73342396b9a3ac6fe140ff478221ecd5c77b0608c48e22cc8afa"
  elsif OS.mac?
    url "https://github.com/buildpacks/pack/releases/download/v0.23.0/pack-v0.23.0-macos.tgz"
    sha256 "08e67ff2968e83a7a21021243b78cd93cfd9c7129f9d7e4c843adad767b0fdee"
  else 
    url "https://github.com/buildpacks/pack/releases/download/v0.23.0/pack-v0.23.0-linux.tgz"
    sha256 "d1278982cf4ec8ab2e1fb20348c756c527910eae1312774b5c681a33970375ee"
  end

  def install
    bin.install "pack"
  end
end
